export const LOAD_COURSES_REQUEST = "LOAD_COURSES_REQUEST"
export const LOAD_COURSES_SUCCESS = "LOAD_COURSES_SUCCESS"
export const LOAD_COURSES_FAILED = "LOAD_COURSES_FAILED"
export const ADD_COURSE_REQUEST = "ADD_COURSE_REQUEST"
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS"
export const ADD_COURSE_FAILED = "ADD_COURSE_FAILED"

export const ADD_GROUP_REQUEST = "ADD_GROUP_REQUEST"
export const ADD_GROUP_SUCCESS = "ADD_GROUP_SUCCESS"
export const ADD_GROUP_FAILED = "ADD_GROUP_FAILED"
export const LOAD_GROUPS_REQUEST = "LOAD_GROUPS_REQUEST"
export const LOAD_GROUPS_SUCCESS = "LOAD_GROUPS_SUCCESS"
export const LOAD_GROUPS_FAILED = "LOAD_GROUPS_FAILED"

export const ADD_GROUP_MEMBER = "ADD_GROUP_MEMBER";
export const DELETE_GROUP_MEMBER = "DELETE_GROUP_MEMBER"
export const CHANGE_GROUP_MEMBER = "CHANGE_GROUP_MEMBER"

export const LOAD_ARCHIVED_REQUEST = "LOAD_ARCHIVED_REQUEST"
export const LOAD_ARCHIVED_SUCCESS = "LOAD_ARCHIVED_SUCCESS"
export const LOAD_ARCHIVED_FAILED = "LOAD_ARCHIVED_FAILED"
export const ARCHIVE_GROUP_REQUEST = "ARCHIVE_GROUP_REQUEST"
export const ARCHIVE_GROUP_SUCCESS = "ARCHIVE_GROUP_SUCCESS"
export const ARCHIVE_GROUP_FAILED = "ARCHIVE_GROUP_FAILED"

export const DELETE_GROUP_REQUEST = "DELETE_GROUP_REQUEST"
export const DELETE_GROUP_SUCCESS = "DELETE_GROUP_SUCCESS"
export const DELETE_GROUP_FAILED = "DELETE_GROUP_FAILED"

export const LOAD_EARNINGS_CHART_REQUEST = "LOAD_EARNINGS_CHART_REQUEST"
export const LOAD_EARNINGS_CHART_SUCCESS = "LOAD_EARNINGS_CHART_SUCCESS"
export const LOAD_EARNINGS_CHART_FAILED = "LOAD_EARNINGS_CHART_FAILED"

export const ADD_CHART_EARNING_REQUEST = "ADD_CHART_EARNING_REQUEST"
export const ADD_CHART_EARNING_SUCCESS = "ADD_CHART_EARNING_SUCCESS"
export const ADD_CHART_EARNING_FAILED = "ADD_CHART_EARNING_FAILED"

export const ADD_EARNING_REQUEST = "ADD_EARNING_REQUEST"
export const ADD_EARNING_SUCCESS = "ADD_EARNING_SUCCESS"
export const ADD_EARNING_FAILED = "ADD_EARNING_FAILED"

export const LOAD_EARNINGS_REQUEST = "LOAD_EARNINGS_REQUEST"
export const LOAD_EARNINGS_SUCCESS = "LOAD_EARNINGS_SUCCESS"
export const LOAD_EARNINGS_FAILED = "LOAD_EARNINGS_FAILED"

export const ADD_EXPENSE_REQUEST = "ADD_EXPENSE_REQUEST"
export const ADD_EXPENSE_SUCCESS = "ADD_EXPENSE_SUCCESS"
export const ADD_EXPENSE_FAILED = "ADD_EXPENSE_FAILED"

export const LOAD_EXPENSES_REQUEST = "LOAD_EXPENSES_REQUEST"
export const LOAD_EXPENSES_SUCCESS = "LOAD_EXPENSES_SUCCESS"
export const LOAD_EXPENSES_FAILED = "LOAD_EXPENSES_FAILED"

export const LOAD_EXPENSES_CHART_REQUEST = "LOAD_EXPENSES_CHART_REQUEST"
export const LOAD_EXPENSES_CHART_SUCCESS = "LOAD_EXPENSES_CHART_SUCCESS"
export const LOAD_EXPENSES_CHART_FAILED = "LOAD_EXPENSES_CHART_FAILED"

export const ADD_CHART_EXPENSE_REQUEST = "ADD_CHART_EXPENSE_REQUEST"
export const ADD_CHART_EXPENSE_SUCCESS = "ADD_CHART_EXPENSE_SUCCESS"
export const ADD_CHART_EXPENSE_FAILED = "ADD_CHART_EXPENSE_FAILED"

export const AUTH_REQUEST = "AUTH_REQUEST"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAILED = "AUTH_FAILED"
export const AUTH_LOGOUT = "AUTH_LOGOUT"
